### PR TITLE
Finished the initial HTML for the home page / No styles yet

### PR DESCRIPTION
**Pull request by EmilioColds**
Created the HTML for the home page with specific IDs, linked with TailWind styles sheet and Font Awesome page, linked the CSS and JavaScript files.

### CODE REVIEW

**Comment by BryanGC96** [comment]
Todo se ve bien!

**Review by BryanGC96 — APPROVED** [review]
All looks good!

**Comment by juliogallegosv** [comment]
LGTM

**Review by juliogallegosv — COMMENTED** [review]
All good

**Review by juliogallegosv — APPROVED** [review]

**Pull request merged**
